---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doubler-service
  namespace: microservices
  labels:
    app.kubernetes.io/name: doubler-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: doubler-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doubler-service
    spec:
      containers:
      - name: doubler-service
        image: ghcr.io/lukehouge/doubler-service:latest
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: MIN_DELAY_SECONDS
          value: "3"
        - name: MAX_DELAY_SECONDS
          value: "7"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: doubler-service
  namespace: microservices
  labels:
    app.kubernetes.io/name: doubler-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  selector:
    app.kubernetes.io/name: doubler-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: doubler-service-hpa
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doubler-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60