---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: microservices
  labels:
    app.kubernetes.io/name: fastapi-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: fastapi-app=ghcr.io/lukehouge/fastapi-app
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: ghcr.io/lukehouge/fastapi-app:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: DOUBLER_SERVICE_URL
          value: "http://doubler-service:8001"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: microservices
  labels:
    app.kubernetes.io/name: fastapi-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30082
    name: http
  selector:
    app.kubernetes.io/name: fastapi-app